# Generated by Django 5.0.3 on 2024-04-04 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_room_messagedepartment_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionsChat',
            new_name='Department',
        ),
        migrations.AlterField(
            model_name='messagedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_messages', to='chat.departmentchat'),
        ),
        migrations.AlterField(
            model_name='messagedepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameModel(
            old_name='DepartmentChat',
            new_name='Region',
        ),
        migrations.CreateModel(
            name='MessageRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_Added', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_messages', to='chat.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_Added',),
            },
        ),
        migrations.DeleteModel(
            name='MessageRegions',
        ),
    ]
