# Generated by Django 5.0.3 on 2024-04-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_regionschat_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_messages', to='chat.department'),
        ),
    ]
