# Generated by Django 5.0.3 on 2024-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messagedepartment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedepartment',
            name='key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='messageregion',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
