# Generated by Django 5.0.3 on 2024-04-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messagedepartment_key_messageregion_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagedepartment',
            options={'ordering': ('-date_Added',)},
        ),
        migrations.AlterModelOptions(
            name='messageregion',
            options={'ordering': ('-date_Added',)},
        ),
    ]
